<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>10. The Church: Instrument of the Kingdom </title>
</head>

<body>
  <!--#include virtual="/include/logo_and_top_address.htm"-->
      <P align="right"><img border="0" src="Beliefs__doctrine_name.jpg"></P>
      <!--#include virtual="/include/who_we_are_links.htm"-->
      <!--#include virtual="/include/main_links_all.htm"-->

        <br></br>
        <p align="center"><font color="#FFFFFF" face="Arial" size="3"><a href="beliefs.asp"><span style="mso-bidi-font-weight: normal"><b>Back to beliefs</b></span></a></font></p>
        <P align=right><FONT face="Arial, Helvetica, sans-serif" color=#ffffff size=2>&nbsp;&nbsp;&nbsp;&nbsp;</FONT></P>
        <p align="left"><b><font color="#FFFFFF" face="Arial" size="4">&nbsp;&nbsp;A more detailed explanation of:</font></b></p>
        
     
      <DIV align=center>
        <p class="bodytext"><b><font face="Arial" size="3">10. The Church: Instrument of the Kingdom </font></b></p>
        <p class="MsoNormal" style="margin-left:0in;text-align:justify;text-indent:
-.25in;mso-hyphenate:none;tab-stops:.25in .5in .75in"><span style="font-size:
10.0pt;letter-spacing:-.1pt"><span style="mso-tab-count:1">&nbsp;&nbsp;&nbsp;&nbsp;
        </span>
        &nbsp;WE BELIEVE in the one,144 holy,145 universal Church.146 All who repent of their sins and 
confess Jesus as Lord and Savior are regenerated by the Holy Spirit147 and form the 
living Body of Christ,148 of which He is the head149 and of which we are all members.150 
<o:p>
        </o:p>
        </span><span style="font-size:10.0pt;letter-spacing:-.1pt"></o:p>
        </span></p>
        <p class="MsoNormal" style="margin-left:0in;text-align:justify;mso-hyphenate:
none;tab-stops:.25in"><span style="font-size:10.0pt;letter-spacing:-.1pt">144John 17:20-21; Ephesians 4:3-6; 1451 Corinthians 3:16-17; 146Matthew 16:17-18; 1 Corinthians 
1:2; Ephesians 2:18-19; 1 Peter 2:9-10; 147Titus 3:4-7; 148Romans 12:4-5; 149Ephesians 1:22; 
Ephesians 5:23; 1501 Corinthians 12:27 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<br /><o:p>
        </o:p>
        </span></p>
        
        <p class="MsoNormal" style="text-align:justify;text-indent:.75in;mso-hyphenate:
none;tab-stops:.25in .5in .75in 1.0in 1.25in 1.5in"><span style="font-size:10.0pt"><span style="letter-spacing:-.1pt"><o:p>
        </o:p>
        </span></span></p>
        <p align="left"><b style="mso-bidi-font-weight:normal"><span style="font-size:12.0pt"><o:p>
        </o:p>
        </span></b>
        </p>
      </DIV>
  <TR>
    <TD style="padding-left: 5px; padding-right: 5px" 
    background="tier2_05.gif" colSpan=3 
    height=19 width="780"><FONT face="Arial, Helvetica, sans-serif">
      <P><FONT face="Arial, Helvetica, sans-serif" color=#ffffff 
      size=2><BR></FONT></P></FONT></TD></TR>
  <TR>
    <TD background="tier2_06.gif" 
    colSpan=3><div align="center" class="levels">
       <!--#include virtual="/include/bottommenu.htm"-->
</div></TD>
  </TR>
  <TR>
    <TD height=2 width="352"><IMG height=1 alt="" 
      src="images/spacer.gif" width=350></TD>
    <TD width="221"><IMG height=1 alt="" 
      src="images/spacer.gif" width=84></TD>
    <TD width="348"><IMG height=1 alt="" 
      src="images/spacer.gif" 
  width=346></TD></TR></TBODY></TABLE><!-- End ImageReady Slices -->

</body>

</html>
